#!/usr/bin/env python3
"""Generate src/installer_font.h from a console PSF font.

The installer draws its own text so it needs no SDL2_ttf (which is not present
on every CFW). We embed printable ASCII (32..126) from Terminus Bold 16 as a
1-bit-per-pixel bitmap: 95 glyphs x 16 rows x 1 byte (the font is 8px wide).
This runs at authoring time only; the generated header is committed.
"""
import gzip, struct, sys, os

SRC = "/usr/share/consolefonts/Lat15-TerminusBold16.psf.gz"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "installer_font.h")
FIRST, LAST = 32, 126

data = gzip.open(SRC, "rb").read()

if data[:2] == b"\x36\x04":                       # PSF1
    charsize = data[3]
    width, height, start, count = 8, charsize, 4, 256
elif data[:4] == b"\x72\xb5\x4a\x86":             # PSF2
    (ver, hdrsize, flags, length,
     charsize, height, width) = struct.unpack_from("<IIIIIII", data, 4)
    start, count = hdrsize, length
else:
    sys.exit("unrecognised PSF magic: %r" % data[:4])

if width != 8:
    sys.exit("expected an 8px-wide font, got %d" % width)
bytes_per_row = (width + 7) // 8
glyph_bytes = charsize

rows = []
for cp in range(FIRST, LAST + 1):
    if cp >= count:
        sys.exit("font has no glyph for %d" % cp)
    g = data[start + cp * glyph_bytes : start + cp * glyph_bytes + glyph_bytes]
    rows.append((cp, g[:height]))

with open(OUT, "w") as f:
    f.write("/* Generated by scripts/gen-installer-font.py — do not edit.\n")
    f.write(" * Source: %s\n" % SRC)
    f.write(" * Terminus is licensed under the SIL Open Font License 1.1.\n")
    f.write(" * Printable ASCII %d..%d, %dx%d, 1bpp, one byte per row.\n */\n"
            % (FIRST, LAST, width, height))
    f.write("#ifndef INSTALLER_FONT_H\n#define INSTALLER_FONT_H\n\n")
    f.write("#define FONT_W %d\n#define FONT_H %d\n" % (width, height))
    f.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n\n" % (FIRST, LAST))
    f.write("static const unsigned char font_bits[%d][%d] = {\n" % (len(rows), height))
    for cp, g in rows:
        ch = chr(cp)
        label = "space" if ch == " " else ("'%s'" % ch if ch not in "\\'" else "0x%02x" % cp)
        f.write("    { %s }, /* %s */\n"
                % (", ".join("0x%02x" % b for b in g), label))
    f.write("};\n\n#endif /* INSTALLER_FONT_H */\n")

print("wrote %s: %d glyphs, %dx%d" % (OUT, len(rows), width, height))
